version: '3'

services:
  traefik:
    build:
      context: ./bin/traefik
      args:
        - BASIC_AUTH_USERNAME=$BASIC_AUTH_USERNAME
        - BASIC_AUTH_PASSWORD=$BASIC_AUTH_PASSWORD
    container_name: "traefik.${DOMAIN-docker-host}"
    restart: unless-stopped
    command: -c /dev/null --api --docker --logLevel=DEBUG --acme.email=$EMAIL --configFile=/etc/traefik/traefik.toml
    ports:
      - 80:80
      - 443:443
      - 8025:8025
    expose:
      - 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/etc/traefik:/etc/traefik
    labels:
      traefik.enable: "true"
      traefik.backend: traefik
      traefik.frontend.rule: "Host:traefik.${DOMAIN-docker-host}"
      traefik.port: "8080"

  portainer:
    image: portainer/portainer
    container_name: "portainer.${DOMAIN-docker-host}"
    restart: unless-stopped
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      # Use the following yaml formatting to allow our basic auth
      # variables to be properly escaped
      - "traefik.backend=portainer"
      - "traefik.port=9000"
      - "traefik.frontend.rule=Host:portainer.${DOMAIN-docker-host}"
      - 'traefik.frontend.auth.basic=${BASIC_AUTH_USERNAME}:${BASIC_AUTH_PASSWORD_ENCRYPTED}'
    depends_on:
      - traefik

  mariadb:
    image: mariadb:10.3.6
    container_name: "mariadb.${DOMAIN-docker-host}"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      # Only specify the DB_NAME if we want a db created with this name
      MYSQL_DATABASE: "${DB_NAME}"
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./volumes/var/lib/mysql:/var/lib/mysql
    depends_on:
      - traefik

  redis:
    image: redis:4.0.9-alpine
    container_name: "redis.${DOMAIN-docker-host}"
    volumes:
      - ./volumes/data:/data
    depends_on:
      - traefik

  web:
    build:
      context: ./bin/web
      args:
        - REDIS_PORT=tcp://redis:6379
    container_name: "web.${DOMAIN-docker-host}"
    environment:
      # Set locale to UTF-8 (https://oncletom.io/2015/docker-encoding/)
      LANG: C.UTF-8
      # REDIS is linked
      REDIS_HOST: redis
      # DB is linked
      DB_HOST: mariadb
      DB_NAME: "${DB_NAME}"
      DB_PORT: 3306
      DB_USER: "${DB_USERNAME}"
      DB_PASS: "${DB_PASSWORD}"
    restart: unless-stopped
    volumes:
      - ./site/craft:/usr/share/nginx/craft
      - ./site/html:/usr/share/nginx/html:ro
    labels:
      traefik.backend: "web"
      traefik.port: "80"
      traefik.frontend.rule: "Host:web.${DOMAIN-docker-host}"
      traefik.frontend.passHostHeader: "true"
    depends_on:
      - mariadb
      - redis
