- hosts: remote
  remote_user: deploy
  become: true
  become_user: root
  become_method: sudo

  roles:
    # We presume we've already run ansible-role-users and ansible-role-common
    - { role: "ansible-docker", tags: "docker" }
